
###############################################################################
#
# Inclusive Makefile for the x86_64_cel_redstone_xp module.
#
# Autogenerated 2017-07-02 02:08:35.774411
#
###############################################################################
x86_64_cel_redstone_xp_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_cel_redstone_xp_BASEDIR)module/make.mk
include $(x86_64_cel_redstone_xp_BASEDIR)module/src/make.mk
include $(x86_64_cel_redstone_xp_BASEDIR)module/auto/make.mk

