
###############################################################################
#
# Inclusive Makefile for the x86_64_cel_ericsson_nru03 module.
#
# Autogenerated 2020-1-13 05:13:18.533898
#
###############################################################################
x86_64_cel_ericsson_nru03_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_cel_ericsson_nru03_BASEDIR)module/make.mk
include $(x86_64_cel_ericsson_nru03_BASEDIR)module/src/make.mk
include $(x86_64_cel_ericsson_nru03_BASEDIR)module/auto/make.mk

