
###############################################################################
#
# Inclusive Makefile for the libonlp-x86-64-cel-redstone-xp-r0 module.
#
# Autogenerated 2015-12-23 00:41:39.666568
#
###############################################################################
libonlp-x86-64-cel-redstone-xp-r0_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

